#!/bin/sh

groupmod -g $(stat -c '%u' /app) www-data
usermod -u $(stat -c '%u' /app) -g $(stat -c '%u' /app) www-data

test -f /app/vendor/autoload.php || composer install

php -S 0.0.0.0:8337 -t public
