### Login - need get jwt token
POST http://127.0.0.1:8337/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

> {% client.global.set("auth_token", response.body.token); %}

### Check coupon
POST http://127.0.0.1:8337/api/coupon-validate
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "coupon": "P20"
}

### Calculate Price
POST http://127.0.0.1:8337/api/calculate-price
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "P10"
}

### Execute Purchase
POST http://127.0.0.1:8337/api/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}
